[project]
name = 'Solar-Energy-Insurance-Platform'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.performance-analytics]
path = 'contracts/performance-analytics.clar'
clarity_version = 3
epoch = 'latest'

[contracts.weather-production-oracle]
path = 'contracts/weather-production-oracle.clar'
clarity_version = 3
epoch = '3.2'

[contracts.yield-protection-engine]
path = 'contracts/yield-protection-engine.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
